development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: OnlineUsersSimpleExample_development

test:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: OnlineUsersSimpleExample_test

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: OnlineUsersSimpleExample_production
